# Generated by Django 2.1.3 on 2018-11-21 08:16

from django.db import migrations, models
import django.db.models.deletion
import egov_hr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_reference', models.CharField(default=egov_hr.models.get_uniqueId, max_length=15)),
                ('contract_type', models.CharField(choices=[('Full-Time', 'FTIM'), ('Part-Time', 'PTIM'), ('Fixed-Term', 'FTER'), ('Agency Staff', 'AGEN'), ('Freelancer', 'FREE'), ('Consultant', 'CSUL'), ('Controctor', 'COTR'), ('Volunteer', 'VOLU')], max_length=10)),
                ('contract_title', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='Expire Date')),
                ('gross_base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_contract',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=5, unique=True, verbose_name='Department Code')),
                ('department_name', models.CharField(max_length=100, verbose_name='Department Name')),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Dependant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'hr_address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_ref', models.CharField(default=egov_hr.models.get_uniqueId, max_length=15, primary_key=True, serialize=False, verbose_name='Employee Code')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Miss', 'Miss')], max_length=10, verbose_name='Title')),
                ('first_name', models.CharField(max_length=80, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=80, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=80, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=80, verbose_name='Gender')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('date_hire', models.DateField(verbose_name='Date Hire')),
                ('image', models.ImageField(default='default.png', upload_to='employee_pics')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('county', models.CharField(choices=[('Bomi', 'Bomi'), ('Bong', 'Bong'), ('Gbar', 'Gbarpolu'), ('GBas', 'Grand Bassa'), ('Cape', 'Grand Cape Mount'), ('Gged', 'Grand Gedeh'), ('Gkru', 'Grand Kru'), ('Lofa', 'Lofa'), ('Marg', 'Margibi'), ('Mary', 'Maryland'), ('Mont', 'Montserrado'), ('Nimb', 'Nimba'), ('Rces', 'Rivercess'), ('Rgee', 'River Gee'), ('Sino', 'Sinoe')], max_length=4)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('recorded_on', models.DateTimeField(auto_now=True)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_hr.Department')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'hr_employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_ref', models.CharField(max_length=100, verbose_name='Job Reference')),
                ('title', models.CharField(max_length=150, verbose_name='Job Title')),
            ],
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_hr.Employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_hr.Job')),
            ],
            options={
                'verbose_name': 'Job History',
                'verbose_name_plural': 'Job Histories',
                'db_table': 'hr_jobhistory',
            },
        ),
        migrations.CreateModel(
            name='MinistryAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_code', models.CharField(max_length=5, verbose_name='Entity Code')),
                ('entity_name', models.CharField(max_length=100, verbose_name='Ministry / Agency Name')),
            ],
            options={
                'verbose_name': 'Ministry / Angency',
                'verbose_name_plural': 'Gov Entities',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='ministry_or_angency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_hr.MinistryAgency'),
        ),
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_hr.Employee'),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('contract_reference', 'employee')},
        ),
    ]
