# Generated by Django 2.1.3 on 2018-11-25 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egov_ams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='vdr_category',
        ),
        migrations.AlterModelTable(
            name='manufacturer',
            table='vrd_manufacturer',
        ),
    ]
