# Generated by Django 2.1.3 on 2018-11-21 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('egov_hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_number', models.CharField(max_length=10)),
                ('cell_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_log_number', models.CharField(max_length=20)),
                ('full_name_complainant', models.CharField(blank=True, max_length=200, null=True)),
                ('complainant_statement', models.TextField(blank=True, null=True)),
                ('defendant_statement', models.TextField(blank=True, null=True)),
                ('current_date_time', models.DateTimeField(auto_now=True)),
                ('date_of_incidence', models.DateField(auto_now_add=True)),
                ('arrest_made', models.BooleanField()),
                ('number_of_arrest_made', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ComplainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complain_category_code', models.CharField(max_length=10)),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('incidence_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date_of_incidence', models.DateField(auto_now_add=True)),
                ('information_source', models.CharField(max_length=200)),
                ('time_recorded', models.DateTimeField(auto_now=True)),
                ('incidence_location', models.CharField(blank=True, max_length=200, null=True)),
                ('name_of_person_reporting', models.CharField(blank=True, max_length=150, null=True)),
                ('reporter_telephone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.CharField(blank=True, max_length=254, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='IncidenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidence_type_code', models.CharField(max_length=10)),
                ('incidence_type_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InformationSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_source_code', models.CharField(max_length=5)),
                ('information_source_name', models.CharField(max_length=130)),
                ('information_source_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inmate',
            fields=[
                ('prisoner_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=2)),
                ('date_of_birth', models.DateField(auto_now_add=True, verbose_name='Date of Birth')),
                ('place_of_birth', models.CharField(max_length=150, verbose_name='Place of Birth')),
                ('inmate_address', models.CharField(blank=True, max_length=150, null=True)),
                ('probation_hearing_due_date', models.DateField(auto_now_add=True, null=True)),
                ('inmate_photo', models.ImageField(upload_to=None)),
                ('note', models.TextField()),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='InmateFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disablity', models.BooleanField(default=False)),
                ('prisoner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_cms.Inmate')),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=2)),
                ('date_of_birth', models.DateField(auto_now_add=True, verbose_name='Date of Birth')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offence',
            fields=[
                ('offence_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('offence_short_name', models.CharField(max_length=50)),
                ('offence_fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('offence_description', models.CharField(blank=True, max_length=200, null=True)),
                ('min_sentence', models.CharField(blank=True, max_length=10, null=True)),
                ('max_sentence', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OffenceCategory',
            fields=[
                ('offence_category_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('offence_category_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='egov_hr.Employee')),
                ('officer_number', models.CharField(max_length=20)),
            ],
            bases=('egov_hr.employee',),
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('electoral_zone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Prison',
            fields=[
                ('prison_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('prison_superintendent', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=70)),
                ('county', models.CharField(choices=[('Bomi', 'Bomi County'), ('Bong', 'Bong County'), ('Gbpl', 'Gbarpolu County'), ('Grba', 'Grand Bassa County'), ('Grcm', 'Grand Cape Mount County'), ('Gcmt', 'Grand Gedeh County'), ('Grkr', 'Grand Kru County'), ('Lofa', 'Lofa County'), ('Marg', 'Margibi County'), ('Marl', 'Maryland County'), ('Mont', 'Montserrado County'), ('Nimb', 'Nimba County'), ('Rivc', 'Rivercess County'), ('Rivg', 'River Gee County'), ('Sino', 'Sinoe County')], max_length=5)),
                ('capacity', models.IntegerField(blank=True, verbose_name='Prison Capacity')),
                ('telephone1', models.CharField(max_length=15)),
                ('telephone2', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_cms.Cell')),
            ],
        ),
        migrations.CreateModel(
            name='PrisonStaff',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='egov_hr.Employee')),
                ('prison_assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_cms.Prison')),
            ],
            bases=('egov_hr.employee',),
        ),
        migrations.CreateModel(
            name='PrisonStaffRoles',
            fields=[
                ('prison_staff_role_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('role_code_description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_code', models.CharField(max_length=5)),
                ('relationship_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitor_name', models.CharField(max_length=150)),
                ('name_company', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=130, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='prisonstaff',
            name='prison_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_cms.PrisonStaffRoles'),
        ),
        migrations.AddField(
            model_name='offence',
            name='offence_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_cms.OffenceCategory'),
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='relationship_to_inmate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_cms.RelationshipType'),
        ),
        migrations.AddField(
            model_name='inmatefamily',
            name='Next_of_kin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_cms.NextOfKin'),
        ),
        migrations.AddField(
            model_name='inmatefamily',
            name='prisoner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_cms.Inmate'),
        ),
        migrations.AddField(
            model_name='inmate',
            name='next_of_kin',
            field=models.ManyToManyField(through='egov_cms.InmateFamily', to='egov_cms.NextOfKin'),
        ),
        migrations.AddField(
            model_name='inmate',
            name='offence',
            field=models.ManyToManyField(to='egov_cms.Offence'),
        ),
        migrations.AddField(
            model_name='inmate',
            name='prison_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_cms.Prison'),
        ),
        migrations.AddField(
            model_name='inmate',
            name='solicitor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_cms.Solicitor'),
        ),
        migrations.AddField(
            model_name='incidence',
            name='officer_incharged',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_cms.Officer'),
        ),
        migrations.AddField(
            model_name='incidence',
            name='type_of_incidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_cms.IncidenceType'),
        ),
        migrations.AddField(
            model_name='complain',
            name='information_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_cms.InformationSource'),
        ),
        migrations.AddField(
            model_name='complain',
            name='nature_of_complain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_cms.ComplainCategory'),
        ),
        migrations.AddField(
            model_name='complain',
            name='officer_on_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_cms.Officer'),
        ),
    ]
