# Generated by Django 2.1.3 on 2018-11-25 23:02

from django.db import migrations, models
import django.db.models.deletion
import egov_vrd.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_ref', models.CharField(default=egov_vrd.models.get_uniqueId, max_length=20, verbose_name='Owner Reference')),
                ('individual_owner_or_company', models.BooleanField(default=False, verbose_name='Individual or Company')),
                ('owner_name', models.CharField(blank=True, help_text='Leave blank if Individual', max_length=180, null=True, verbose_name='Organization Or Company Name')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('Female', 'F'), ('Male', 'M'), ('Not Specified', 'N')], max_length=1, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, verbose_name='Date of Birth')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('county', models.CharField(max_length=100, verbose_name='County')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telephone')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
                'db_table': 'vrd_owner',
            },
        ),
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_category_code', models.CharField(max_length=4, verbose_name='Tax Category Code')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Tax Category',
                'verbose_name_plural': 'Tax Categories',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_registration_ref', models.CharField(default=egov_vrd.models.get_uniqueId, max_length=20, verbose_name='Vehicle Registration Reference')),
                ('plate_number', models.CharField(max_length=10, verbose_name='Plate Number')),
                ('vin_number', models.CharField(max_length=30, verbose_name='VIN Number')),
                ('current_milage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Current Milage')),
                ('vehicle_color', models.CharField(max_length=20, verbose_name='Vehicle Color')),
                ('engine_size', models.CharField(blank=True, choices=[('1.2', '1.2'), ('2.0', '2.0'), ('3.0', '3.0'), ('4.0', '4.0'), ('5.0', '5.0'), ('HD', 'Heavy Duty')], max_length=10, null=True, verbose_name='Enigine Size')),
                ('transmission', models.CharField(choices=[('Manuel', 'Manuel'), ('Automatic', 'Automatic'), ('Semi Auto', 'Semi Auto')], max_length=10, verbose_name='Transmission')),
                ('fuel_type', models.CharField(choices=[('Gasoline', 'Gas'), ('Diesel', 'Dsl'), ('Electric', 'Ele'), ('Bio-Fuel', 'Bio')], max_length=10, verbose_name='Fuel Type')),
                ('tax_category_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_vrd.TaxCategory')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vrd_vehicle',
            },
        ),
        migrations.CreateModel(
            name='VehicleOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_on', models.DateTimeField(auto_now_add=True)),
                ('ownership_transfer_date', models.DateField(blank=True, verbose_name='Transfer on')),
                ('status', models.CharField(default='Active', max_length=10, verbose_name='Status')),
                ('note', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_vrd.Owner')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_vrd.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=5, verbose_name='Type Code')),
                ('type_name', models.CharField(max_length=100, verbose_name='Type Name')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egov_vrd.VehicleType'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleownership',
            unique_together={('owner', 'vehicle')},
        ),
    ]
